### PR TITLE
Rusty roguelike macroquad

### PR DESCRIPTION
**Pull request by ollej**
An implementation in Macroquad of the Rusty Roguelike from the book Hands-on Rust by Herbert Wolverson.

### CODE REVIEW

**Comment by 64kramsystem** [comment]
Yikes. That was fast :sweat_smile:.

It's going to take some time to review; sorry for this, but these are reference projects, and this project is also in its infancy, so I need to set the standars, put it on my schedule etc. :smile: 

I leave no PR unturned, though :smile: I'll ping you on the next week.

**Comment by erlend-sh** [comment]
The author of Macroquad @not-fl3 might also have ideas for best practices in this example.

**Comment by 64kramsystem** [comment]
> The author of Macroquad @not-fl3 might also have ideas for best practices in this example.

That's a very good idea. What do you think of adding the engine maintainers as collaborators with read permissions, so that they could be requested to review (assuming I understand the collator permissions correctly), if they agree?

**Comment by ollej** [comment]
Yeah, I’m pretty sure it’s not up to par for best practices in neither Macroquad nor Rust. It might need some work to be a good example.

**Comment by 64kramsystem** [comment]
> Yeah, I’m pretty sure it’s not up to par for best practices in neither Macroquad nor Rust. It might need some work to be a good example.

Interesting, this is actually the project with Bracket-lib replaced by Macroquad (I thought the ECS part was ripped out, but it's been kept, which is ok, of course).

I'm in the process of updating the rust-game-ports project for general release, and discuss the port design priciples etc. (see starter [here](https://github.com/rust-gamedev/wg/issues/127#issuecomment-1204895319)). I'll ping back once the discussions are done :smile:

**Comment by 64kramsystem** [comment]
I've had a first look and I think it looks good. The good side of immediate mode libraries is that there's really nothing to design, so it's hard to get it fundamentally wrong :joy:

We're in the process of defining the acceptance guidelines, most importantly, the high level ones (I'm done with the low level ones, which I think are reasonable). After they're set, I/we are going to have a better look, then we'll follow up :smile:

**Review by 64kramsystem — APPROVED** [review]
Looks good! Thanks for the contribution :relaxed: 

I've solved the conflicts; will merge shortly.

**Pull request merged**
